name: FiveUI
version: 'Alpha-1.0'
main: com.github.drfiveminusmint.fiveUI.FiveUI
api-version: '1.21'
author: drfiveminusminus
commands:
  fiveui:
    aliases:
      - 5ui
    description: Display FiveUI version
    usage: /fiveui
